spring:
  profiles:
    include: secret

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delavery?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: 3615

  flyway:
    enabled: true
    baseline-on-migrate: true